//Types for Authentication
//Account Creation
export const START_ACCOUNT_CREATION = 'START_ACCOUNT_CREATION'
export const STOP_ACCOUNT_CREATION = 'STOP_ACCOUNT_CREATION'
export const ERROR_WHEN_CREATING_ACCOUNT = 'ERROR_WHEN_CREATING_ACCOUNT'

//Account Logging
export const START_LOG_INTO_ACCOUNT = 'START_LOG_INTO_ACCOUNT'
export const STOP_LOG_INTO_ACCOUNT = 'STOP_LOG_INTO_ACCOUNT'
export const LOG_OFF_ACCOUNT = 'LOG_OFF_ACCOUNT'
export const ERROR_WHEN_LOGGING = 'ERROR_WHEN_LOGGING'
